#!/bin/bash

# INSTALL-CERTIFICATES

sudo apt-get install --no-install-recommends --no-install-suggests -y ca-certificates dirmngr gpg-agent apt-transport-https

# UPDATE-SYSTEM

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
sudo apt-get full-upgrade -y

# MY-APPS

sudo apt-get install --no-install-recommends --no-install-suggests -y xserver-xorg xinit x11-xserver-utils xutils htop powertop udisks2 udiskie ntfs-3g conky kodi xfce4-settings xterm android-tools-adb android-tools-fastboot iptables wget curl git lbzip2 bzip2 p7zip xarchiver engrampa unrar unzip thunar thunar-volman gvfs gvfs-backends gvfs-fuse gnome-screenshot gnome-disk-utility i3-wm i3status i3lock i3blocks dmenu nitrogen feh scrot weechat znc wireguard-tools openvpn network-manager-gnome network-manager network-manager-openvpn network-manager-openvpn-gnome firefox-esr chromium pavucontrol pulseaudio volumeicon-alsa mpv vlc qbittorrent qbittorrent-nox x11-xserver-utils vnstat squid samba smbclient cifs-utils sakura mousepad pcmanfm pcmanfm-qt hexchat hexchat-plugins gnome-icon-theme lxappearance oxygen-icon-theme neofetch zsh rsync nmap screen openssh-server lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings hdparm

# CLEAN-PACKAGES

sudo apt-get autoremove --purge -y
sudo apt-get autoclean -y
sudo apt-get clean -y

# ENABLE-SERVICES

sudo systemctl enable lightdm vnstat smbd

# DISABLE-SERVICES

sudo systemctl disable --now squid nmbd zramswap

# INTERNET-BROWSER

sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
sudo apt-get update -y
sudo apt-get install -y --no-install-recommends --no-install-suggests brave-browser

# CREATE-DIRECTORIES

sudo mkdir -p /home/pi/Downloads/
sudo mkdir -p /home/pi/Pictures/

# INSTALL-WEECHAT

sudo echo "deb [signed-by=/usr/share/keyrings/weechat-archive-keyring.gpg] https://weechat.org/raspbian bookworm main" | sudo tee /etc/apt/sources.list.d/weechat.list
sudo echo "deb-src [signed-by=/usr/share/keyrings/weechat-archive-keyring.gpg] https://weechat.org/raspbian bookworm main" | sudo tee -a /etc/apt/sources.list.d/weechat.list
sudo apt-get update -y
sudo mkdir /root/.gnupg
sudo chmod 700 /root/.gnupg
sudo mkdir -p /usr/share/keyrings
sudo gpg --no-default-keyring --keyring /usr/share/keyrings/weechat-archive-keyring.gpg --keyserver hkps://keys.openpgp.org --recv-keys 11E9DE8848F2B65222AA75B8D1820DB22A11534E
sudo apt-get install --no-install-recommends --no-install-suggests -y weechat-curses weechat-plugins weechat-python weechat-perl

### MESA-GRAPHICS

sudo rm -rf /usr/lib/python3.11/EXTERNALLY-MANAGED
sudo apt-get install --no-install-recommends --no-install-suggests -y python3-pip libxcb-randr0-dev libxrandr-dev \
        libxcb-xinerama0-dev libxinerama-dev libxcursor-dev \
        libxcb-cursor-dev libxkbcommon-dev xutils-dev \
        xutils-dev libpthread-stubs0-dev libpciaccess-dev \
        libffi-dev x11proto-xext-dev libxcb1-dev libxcb-*dev \
        bison flex libssl-dev libgnutls28-dev x11proto-dri2-dev \
        x11proto-dev libx11-dev libxcb-glx0-dev \
        libx11-xcb-dev libxext-dev libxdamage-dev libxfixes-dev \
        libva-dev x11proto-randr-dev x11proto-present-dev \
        libclc-16-dev libelf-dev git build-essential mesa-utils \
        libvulkan-dev ninja-build libvulkan1 python3-mako \
        libdrm-dev libxshmfence-dev libxxf86vm-dev libunwind-dev \
		valgrind libzstd-dev vulkan-tools python3-pip
sudo apt purge meson -y
sudo pip3 install meson 
sudo pip3 install mako
cd ~/Downloads
git clone https://gitlab.freedesktop.org/mesa/mesa.git mesa_vulkan
cd mesa_vulkan
CFLAGS="-mcpu=cortex-a76" CXXFLAGS="-mcpu=cortex-a76" meson --prefix /usr -Dplatforms=x11 -Dvulkan-drivers=broadcom -Ddri-drivers=VC4,V3D -Dgallium-drivers=kmsro,v3d,vc4 -Dbuildtype=release build
ninja -C build -j4
sudo ninja -C build install

# UPDATE-YOUR-SYSTEM

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get full-upgrade -y
sudo apt-get dist-upgrade -y

# INSTALL-STRONGWAN-VPN

sudo apt-get install --no-install-recommends --no-install-suggests -y strongswan libcharon-extra-plugins libstrongswan-extra-plugins libcharon-extauth-plugins resolvconf

# CLEAN-PACKAGES

sudo apt-get autoremove --purge -y
sudo apt-get autoclean -y
sudo apt-get clean -y

# USER-AND-ROOT-PASSWORD-CHANGE

echo Changing password for the user pi...
passwd pi
echo Changing password for the user root...
passwd root

# SAMBA-PASSWORDS

echo Changing samba password for the user pi...
smbpasswd -a pi
echo Changing samba password for the user root...
smbpasswd -a root

# REBOOT-SYSTEM-TO-APPLY

sudo shutdown -r now
