#!/bin/bash

# Change this to match your correct profile
PROFILE="znt4tau6.default-esr115"

cd "/home/pi/.mozilla/firefox-esr"

if test -z "$(mount | grep -F "/home/pi/.mozilla/firefox-esr/${PROFILE}" )"
then
    mount "/home/pi/.mozilla/firefox-esr/${PROFILE}"
fi

if test -f "${PROFILE}/.unpacked"
then
    rsync -av --delete --exclude .unpacked ./"$PROFILE"/ ./profile/
else
    rsync -av ./profile/ ./"$PROFILE"/
    touch "${PROFILE}/.unpacked"
fi

exit
